name: CI Check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Visa meddelande
      run: echo "Hejsan! Detta är en automatisk körning via GitHub Actions"
